# Generated by Django 3.1.3 on 2020-12-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20201209_0631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='borrrower',
            new_name='borrower',
        ),
    ]
